python -c "import cv2;print(cv2.cuda.getCudaEnabledDeviceCount())"
python3 -c "import cv2;print(cv2.cuda.getCudaEnabledDeviceCount())"
dpkg -l | grep "opencv"
python -c "import torch;print(torch.cuda.is_available())"
python -c "print('Tensor device:', target_tensor.device)"